name: _build

on:
  workflow_dispatch:
  
  
env:
  SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}
  SRCCLR_SCM_URI: https://github.com/bnreplah/verademo
  SRCCLR_SCM_SUB_PATH: /app

jobs:
  build:
    runs-on: ubuntu-latest
    # grants permissions for the artifact to be uploaded
    permissions:
      contents: read
      packages: write
    
    
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can acces it and clones the repo
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: |
          pwd
          mvn -B clean package --file pom.xml
          
          
            if-no-files-found: error
   
